---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2024-12-04T21:12:56.745814492-05:00"
  labels:
    kustomize.toolkit.fluxcd.io/name: infrastructure-infrastructure
    kustomize.toolkit.fluxcd.io/namespace: cluster-config
  name: fortiweb-ingress-controller
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: fwb-k8s-ctrl
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fortiweb-ingress-controller
        namespace: cluster-config
      version: 2.0.1
  install:
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: fortiweb-ingress-controller
  targetNamespace: fortiweb-ingress
  values:
    image:
      repository: fortinet/fortiweb-ingress
      tag: "2.0"
